### ISSUE TITLE
gulp --production  error

### ISSUE THREAD

**Issue by shirne** [BootstrapCMS/CMS#184]
module.js:338
    throw err;
          ^
Error: Cannot find module 'orchestrator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (F:\sites\CMS-laravel\node_modules\gulp\index.js:4:20)

    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by GrahamCampbell** [comment]
Any issues with npm are unrelated to us I'm affraid. Sorry.

**Comment by shirne** [comment]
Tks.
