### ISSUE TITLE
While serve application error 500

### ISSUE THREAD

**Issue by raoasifraza11** [BootstrapCMS/CMS#241]
After completing the steps you provided in readme I face the error 500 Internal Server Error can you help me?
![screen shot 2017-10-02 at 1 38 27 pm](https://user-images.githubusercontent.com/18229291/31069708-0cb3b9ce-a777-11e7-8eb8-4bc546e30f05.png)

**Comment by helloMJW** [comment]
### me too 
```
 Stack trace:
nginx_1     | #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/home/www-data/...', 52, Array)
nginx_1     | #1 /home/www-data/bootstrap-cms/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(52): count(NULL)
nginx_1     | #2 /home/www-data/bootstrap-cms/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(78): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
nginx_1     | #3 /home/www-data/bootstrap-cms/bootstrap/cache/compiled.php(1850): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
nginx_1     | #4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
nginx_1     | #5 {main}
nginx_1     |   thrown in /home/www-data/bootstrap-cms/vendor/graham-campbell/exceptions/src/Ex...
nginx_1     | PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/www-data/bootstrap-cms/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:52

```

**Comment by GrahamCampbell** [comment]
This project was built for php 5. It definitely does not work on 7.2.

**Comment by raoasifraza11** [comment]
@GrahamCampbell Thanks 👍
